### ISSUE TITLE
zherk has an incorrect interface

### ISSUE THREAD

**Issue by byornski** [14NGiestas/mfi#7]
The interface from netlib for [zherk](https://www.netlib.org/lapack/explore-html/dc/d17/group__complex16__blas__level3_ga71e68893445a523b923411ebf4c22582.html) says that alpha and beta should be double precision but the generated interface is

> pure subroutine zherk(uplo, trans, n, k, alpha, a, lda, beta, c, ldc)
>     import :: REAL64
>     integer, parameter :: wp = REAL64
>     complex(wp), intent(in) :: a(lda,*)
>     complex(wp), intent(inout) :: c(ldc,*)
>     character, intent(in) :: trans
>     character, intent(in) :: uplo
>     complex(wp), intent(in) :: alpha
>     complex(wp), intent(in) :: beta
>     integer, intent(in) :: n
>     integer, intent(in) :: k
>     integer, intent(in) :: lda
>     integer, intent(in) :: ldc
> end subroutine

with alpha and beta complex which is incorrect

**Comment by 14NGiestas** [comment]
This is a problem with me reusing the same macro for hermitian and symmetric routines which generates such wrong interfaces.
Thank you again for reporting it, I'll be addressing this issue right now.

**Comment by 14NGiestas** [comment]
I think I've fixed the issue with `zherk` [3a35ead](https://github.com/14NGiestas/mfi/commit/3a35eadecd99949054d1d143111c972920cc4ec0).
Some of the macros can be reused for hermitian/symmetric routines and it escaped me that not all of them can.
Please let me know if you find any other in that regard.
